model = "gpt-5.4"
model_reasoning_summary = "auto"
approval_policy = "never"
sandbox_mode    = "danger-full-access"
# sandbox_mode    = "workspace-write"
model_reasoning_effort = "high"
windows_wsl_setup_acknowledged = true
tool_output_token_limit = 50000
file_opener = "vscode"
suppress_unstable_features_warning = true
web_search = "live"
personality = "friendly"
service_tier = "fast"
model_context_window = 400000

[features]
unified_exec = true
shell_snapshot = true
powershell_utf8 = true
steer = true
collaboration_modes = true
apps = true
personality = true
multi_agent = true
responses_websockets_v2 = true
prevent_idle_sleep = true
voice_transcription = true
# memories = true
js_repl = true
default_mode_request_user_input = true

[sandbox_workspace_write]
network_access = true

[tui]
notifications = [ "agent-turn-complete", "approval-requested" ]
status_line = ["git-branch", "context-remaining", "five-hour-limit", "weekly-limit"]
theme = "monokai-extended"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { "CONTEXT7_API_KEY" = "CONTEXT7_API_KEY" }

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"
startup_timeout_sec = 60.0

# [mcp_servers.exa]
# url = "https://mcp.exa.ai/mcp"
# startup_timeout_sec = 60.0

[mcp_servers.gh_grep]
url = "https://mcp.grep.app"
startup_timeout_sec = 60.0

# [mcp_servers.chrome-devtools]
# command = "npx"
# args = ["chrome-devtools-mcp@latest"]
# startup_timeout_sec = 60.0

[notice]
hide_world_writable_warning = true
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[agents]
max_threads = 12
# max_depth = 3

[windows]
sandbox = "elevated"
