model = "gpt-6-astra"
model_reasoning_summary = "auto"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
model_reasoning_effort = "medium"
windows_wsl_setup_acknowledged = true
tool_output_token_limit = 50000
file_opener = "vscode"
suppress_unstable_features_warning = true
web_search = "live"
personality = "friendly"
approvals_reviewer = "user"
# model_context_window = 400000

[features]
unified_exec = true
shell_snapshot = true
apps = true
personality = true
multi_agent = true
prevent_idle_sleep = true
memories = true
default_mode_request_user_input = true
hooks = true
guardian_approval = true
image_generation = true
chronicle = false
goals = true

[sandbox_workspace_write]
writable_roots = []
network_access = true

[tui]
notifications = [ "agent-turn-complete", "approval-requested" ]
status_line = ["git-branch", "context-remaining", "five-hour-limit", "weekly-limit"]
theme = "monokai-extended"

[notice]
fast_default_opt_out = true

[agents]
max_threads = 12
# max_depth = 3

[windows]
sandbox = "elevated"

[memories]
generate_memories = true
use_memories = true
disable_on_external_context = true

[plugins."build-web-apps@openai-curated"]
enabled = true

[plugins."expo@openai-curated"]
enabled = true

[plugins."codex-security@openai-curated"]
enabled = true

[plugins."canva@openai-curated"]
enabled = false

[plugins."hyperframes@openai-curated"]
enabled = true

[plugins."openai-developers@openai-curated"]
enabled = false

[plugins."notion@openai-curated"]
enabled = false

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."build-web-data-visualization@openai-curated"]
enabled = false

[plugins."linear@openai-curated"]
enabled = true

[plugins."wt-agent-hooks@wt-local"]
enabled = false

[plugins."slack@openai-curated"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[apps.connector_68df33b1a2d081918778431a9cfca8ba]
enabled = false

[apps.connector_69312da8e4dc81919370cb86fd172b6c]
enabled = false

[apps.connector_68df038e0ba48191908c8434991bbac2]
enabled = false

[apps.connector_2128aebfecb84f64a069897515042a44]
enabled = false

[apps.asdk_app_69c18c28f1188191bf5b8445c4ab0a2e]
enabled = false

[apps.connector_4aaab2856305417b993eca9a216aaf6e]
enabled = false

[apps.asdk_app_69a1d78e929881919bba0dbda1f6436d]
enabled = true

[apps.connector_2de447f3f15448ebab48783d7e4f5d81]
enabled = false

[apps.asdk_app_69d707a3ef44819185b10b3a43999244]
enabled = false

[apps.asdk_app_69941d065a348191ad84cbb98d8469ec]
enabled = false

[apps.connector_947e0d954944416db111db556030eea6]
enabled = false

[apps.asdk_app_69c3322462288191a4b198f3ff39db2c]
enabled = false

[desktop]
ambient-suggestions-enabled = false
appearanceDarkCodeThemeId = "linear"
sansFontSize = 13
codeFontSize = 12
dictationDictionary = []
localeOverride = "en-US"
notifications-turn-mode = "unfocused"
notifications-permissions-enabled = true
notifications-questions-enabled = true
selected-avatar-id = "custom:chisa-pon"
conversationDetailMode = "STEPS_COMMANDS"
appearanceDiffMarkerStyle = "color"
usePointerCursors = true
keepRemoteControlAwakeWhilePluggedIn = true
show-context-window-usage = true
hotkey-window-projectless-default-enabled = true
git-show-sidebar-pr-icons = false
git-commit-instructions = """
- If the repository defines its own commit conventions, follow those first.
- Otherwise:
  - Write commit messages following [Conventional Commits](https://www.conventionalcommits.org/).
  - Write commit messages in the language specified by the repository. If not explicitly specified, use the language of the README. If there is no README or the language cannot be inferred, use English."""
runCodexInWindowsSubsystemForLinux = false
followUpQueueMode = "queue"
avatar-overlay-mascot-width-px = 103
microphoneInputDeviceId = "fc1032a84c281deaecabddf605b367f9beca50bba22015d814e0a2a3b2a89cb2"
composerEnterBehavior = "cmdAlways"
reduced-motion-preference = "system"
enabled-reasoning-efforts = ["low", "medium", "high", "xhigh", "ultra", "max"]

[desktop.appearanceDarkChromeTheme]
accent = "#606acc"
contrast = 60
ink = "#e3e4e6"
opaqueWindows = false
surface = "#0f0f11"

[desktop.appearanceDarkChromeTheme.fonts]
code = "HackGen"
ui = "Noto Sans JP"

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#69c967"
diffRemoved = "#ff7e78"
skill = "#c2a1ff"

[desktop.open-in-target-preferences]
global = "zed"
